import type { FreelanceOpportunity } from "./types";

export const mockFreelanceGigs: FreelanceOpportunity[] = [
  {
    id: "gig-001",
    title: "Build React Dashboard for SaaS Platform",
    client: "TechStart Inc",
    platform: "freelance",
    platformLabel: "Direct",
    description:
      "Build a responsive data dashboard using React, TypeScript, and Recharts. Integrate with REST API and implement real-time updates via WebSockets.",
    budget: "$8,000 - $12,000",
    location: "Remote",
    remote: true,
    requiredSkills: ["React", "TypeScript", "D3.js", "WebSockets", "REST APIs"],
    matchScore: {
      overall: 88,
      label: "Strong match",
      reasons: [
        "Strong React and TypeScript experience",
        "Previous dashboard projects in portfolio",
        "Available for 4-6 week engagement",
      ],
      missingSkills: ["D3.js"],
    },
    postedAt: "2026-05-28T00:00:00Z",
    deadline: "2026-06-15T00:00:00Z",
    status: "open",
    slug: "react-dashboard-saas",
  },
  {
    id: "gig-002",
    title: "API Integration & Backend Support",
    client: "DataFlow Corp",
    platform: "freelance",
    platformLabel: "Direct",
    description:
      "Help integrate third-party APIs and optimize existing Node.js backend services. Focus on performance, error handling, and documentation.",
    budget: "$5,000 - $8,000",
    location: "Remote",
    remote: true,
    requiredSkills: ["Node.js", "Express", "PostgreSQL", "REST APIs", "Docker"],
    matchScore: {
      overall: 82,
      label: "Strong match",
      reasons: [
        "Strong Node.js and API experience",
        "Experience with PostgreSQL optimization",
        "Flexible on timeline",
      ],
      missingSkills: ["Docker"],
    },
    postedAt: "2026-05-26T00:00:00Z",
    deadline: "2026-06-10T00:00:00Z",
    status: "open",
    slug: "api-integration-backend",
  },
  {
    id: "gig-003",
    title: "Mobile App UI Polish & Animations",
    client: "AppCraft Studio",
    platform: "freelance",
    platformLabel: "Referral",
    description:
      "Polish the UI of a React Native fitness app. Implement smooth animations, improve accessibility, and ensure consistent design across screens.",
    rate: "$85 - $110/hr",
    location: "Remote",
    remote: true,
    requiredSkills: [
      "React Native",
      "TypeScript",
      "Framer Motion",
      "CSS Animations",
      "Figma",
    ],
    matchScore: {
      overall: 75,
      label: "Good match",
      reasons: [
        "React Native experience from past projects",
        "Strong design sensibility",
        "Figma proficient",
      ],
      missingSkills: ["Framer Motion"],
    },
    postedAt: "2026-05-25T00:00:00Z",
    deadline: "2026-06-20T00:00:00Z",
    status: "open",
    slug: "mobile-app-ui-polish",
  },
  {
    id: "gig-004",
    title: "E-commerce Storefront (Next.js)",
    client: "ShopLocal Co",
    platform: "freelance",
    platformLabel: "Platform",
    description:
      "Build a modern e-commerce storefront with Next.js, Stripe integration, and headless CMS. Must support multi-tenant and multi-currency.",
    budget: "$12,000 - $18,000",
    location: "Remote",
    remote: true,
    requiredSkills: [
      "Next.js",
      "TypeScript",
      "Stripe",
      "Tailwind CSS",
      "PostgreSQL",
    ],
    matchScore: {
      overall: 80,
      label: "Good match",
      reasons: [
        "Expertise in Next.js and TypeScript",
        "Previous Stripe integration experience",
        "Available for 6-8 week engagement",
      ],
      missingSkills: [],
    },
    postedAt: "2026-05-24T00:00:00Z",
    deadline: "2026-06-30T00:00:00Z",
    status: "open",
    slug: "ecommerce-storefront",
  },
  {
    id: "gig-005",
    title: "AI Chatbot Integration Consultant",
    client: "SmartHelp Inc",
    platform: "freelance",
    platformLabel: "Direct",
    description:
      "Advise on and implement an AI-powered customer support chatbot using OpenAI API. Scope includes conversation design, error handling, and analytics tracking.",
    rate: "$150 - $200/hr",
    location: "Remote",
    remote: true,
    requiredSkills: [
      "OpenAI API",
      "Node.js",
      "Prompt Engineering",
      "TypeScript",
      "Redis",
    ],
    matchScore: {
      overall: 65,
      label: "Stretch role",
      reasons: [
        "Some API integration experience",
        "Strong Node.js skills",
        "New domain but learnable",
      ],
      missingSkills: ["Prompt Engineering", "Redis"],
    },
    postedAt: "2026-05-22T00:00:00Z",
    status: "open",
    slug: "ai-chatbot-integration",
  },
  {
    id: "gig-006",
    title: "WordPress to Next.js Migration",
    client: "ContentFirst Media",
    platform: "freelance",
    platformLabel: "Platform",
    description:
      "Migrate a high-traffic content site from WordPress to Next.js. Set up headless CMS, preserve SEO rankings, and improve Core Web Vitals.",
    budget: "$6,000 - $10,000",
    location: "Remote",
    remote: true,
    requiredSkills: [
      "Next.js",
      "TypeScript",
      "SEO",
      "Headless CMS",
      "Performance Optimization",
    ],
    matchScore: {
      overall: 78,
      label: "Good match",
      reasons: [
        "Strong Next.js and performance optimization knowledge",
        "SEO experience from past projects",
        "Available immediately",
      ],
      missingSkills: ["Headless CMS"],
    },
    postedAt: "2026-05-20T00:00:00Z",
    deadline: "2026-07-01T00:00:00Z",
    status: "open",
    slug: "wordpress-nextjs-migration",
  },
  {
    id: "gig-007",
    title: "Design System Component Library",
    client: "PixelPerfect Agency",
    platform: "freelance",
    platformLabel: "Referral",
    description:
      "Create a reusable component library in React with Storybook documentation. Must support dark mode, accessibility, and responsive layouts.",
    rate: "$90 - $130/hr",
    location: "Remote",
    remote: true,
    requiredSkills: [
      "React",
      "TypeScript",
      "Storybook",
      "Tailwind CSS",
      "Accessibility",
    ],
    matchScore: {
      overall: 72,
      label: "Good match",
      reasons: [
        "React and TypeScript expertise",
        "Accessibility-aware development practices",
        "Tailwind CSS proficiency",
      ],
      missingSkills: ["Storybook"],
    },
    postedAt: "2026-05-18T00:00:00Z",
    deadline: "2026-06-25T00:00:00Z",
    status: "open",
    slug: "design-system-library",
  },
  {
    id: "gig-008",
    title: "DevOps Infrastructure Setup",
    client: "SecureStack Ltd",
    platform: "freelance",
    platformLabel: "Direct",
    description:
      "Set up CI/CD pipelines, container orchestration, and monitoring for a financial services startup. Must ensure SOC2 compliance.",
    budget: "$15,000 - $25,000",
    location: "Remote",
    remote: true,
    requiredSkills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "CI/CD",
      "Security",
    ],
    matchScore: {
      overall: 45,
      label: "Low match",
      reasons: [
        "Basic AWS knowledge",
        "Limited DevOps experience in portfolio",
        "Security compliance is a significant gap",
      ],
      missingSkills: ["Kubernetes", "Terraform", "Security Compliance"],
    },
    postedAt: "2026-05-26T00:00:00Z",
    deadline: "2026-06-28T00:00:00Z",
    status: "open",
    slug: "devops-infrastructure",
  },
];

export const freelancePlatformOptions = [
  { value: "all", label: "All Platforms" },
  { value: "direct", label: "Direct" },
  { value: "referral", label: "Referral" },
  { value: "platform", label: "Platform" },
];
