import type { ApplicationRecord, SavedJob } from "./types";

export const mockSavedJobs: SavedJob[] = [
  {
    id: "saved-1",
    title: "Senior Software Engineer",
    company: "Vercel",
    location: "San Francisco, CA (Remote)",
    matchScore: 92,
    savedDate: "2026-05-28",
  },
  {
    id: "saved-2",
    title: "Staff Frontend Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    matchScore: 78,
    savedDate: "2026-05-25",
  },
  {
    id: "saved-3",
    title: "Engineering Manager — Platform",
    company: "Stripe",
    location: "San Francisco, CA / Remote",
    matchScore: 85,
    savedDate: "2026-05-22",
  },
  {
    id: "saved-4",
    title: "Full Stack Engineer, Growth",
    company: "Notion",
    location: "New York, NY / Remote",
    savedDate: "2026-05-20",
  },
  {
    id: "saved-5",
    title: "Principal Engineer — Developer Experience",
    company: "GitHub",
    location: "Remote (US)",
    matchScore: 88,
    savedDate: "2026-05-18",
  },
];

export const mockApplications: ApplicationRecord[] = [
  {
    id: "app-1",
    jobId: "saved-1",
    title: "Senior Software Engineer",
    company: "Vercel",
    location: "San Francisco, CA (Remote)",
    status: "applied",
    applicationDate: "2026-05-28",
    coverLetterId: "cl-draft-1",
    nextAction: "Follow up with recruiter",
    reminderDate: "2026-06-04",
    hasResume: true,
    hasCoverLetter: true,
  },
  {
    id: "app-2",
    jobId: "saved-2",
    title: "Staff Frontend Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    status: "resume-tailored",
    applicationDate: "2026-05-29",
    hasResume: true,
    hasCoverLetter: false,
  },
  {
    id: "app-3",
    jobId: "saved-3",
    title: "Engineering Manager — Platform",
    company: "Stripe",
    location: "San Francisco, CA / Remote",
    status: "interviewing",
    applicationDate: "2026-05-15",
    nextAction: "Prepare for technical screen",
    reminderDate: "2026-06-02",
    hasResume: true,
    hasCoverLetter: true,
  },
  {
    id: "app-4",
    jobId: "ext-1",
    title: "Lead Developer Advocate",
    company: "Cloudflare",
    location: "San Francisco, CA / Remote",
    status: "offer",
    applicationDate: "2026-04-20",
    nextAction: "Review offer letter",
    reminderDate: "2026-06-01",
    hasResume: true,
    hasCoverLetter: true,
  },
  {
    id: "app-5",
    jobId: "ext-2",
    title: "Senior Product Engineer",
    company: "Linear",
    location: "Remote",
    status: "rejected",
    applicationDate: "2026-05-10",
    hasResume: true,
    hasCoverLetter: true,
  },
  {
    id: "app-6",
    jobId: "ext-3",
    title: "Founding Engineer",
    company: "Raycast",
    location: "Remote (EU / US)",
    status: "follow-up-needed",
    applicationDate: "2026-05-12",
    nextAction: "Send follow-up email",
    reminderDate: "2026-05-30",
    hasResume: true,
    hasCoverLetter: true,
  },
  {
    id: "app-7",
    jobId: "ext-4",
    title: "Software Engineer — DX",
    company: "Replicate",
    location: "Remote",
    status: "cover-letter-ready",
    applicationDate: "2026-05-30",
    hasResume: true,
    hasCoverLetter: true,
  },
  {
    id: "app-8",
    jobId: "ext-5",
    title: "Senior Backend Engineer",
    company: "Supabase",
    location: "Remote",
    status: "recruiter-contacted",
    applicationDate: "2026-05-26",
    nextAction: "Schedule intro call",
    reminderDate: "2026-06-03",
    hasResume: false,
    hasCoverLetter: false,
  },
];
